[workspace]
channels = ["conda-forge"]
name = "Aptamer2025py"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[dependencies]
matplotlib = ">=3.10.8,<4"
numpy = ">=2.3.5,<3"
pandas = ">=2.3.3,<3"
jupyter = ">=1.1.1,<2"
python = ">=3.12,<3.13"
logomaker = ">=0.8.6,<0.9"
line_profiler = ">=5.0.0,<6"
scikit-learn = ">=1.8.0,<2"

[pypi-dependencies]
adabmdca = ">=0.7,<0.8"
torch = { version = "*" }
