[workspace]
channels = ["conda-forge"]
name = "Aptamer2025py"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[dependencies]
matplotlib = ">=3.10.8,<4"
numpy = ">=2.3.5,<3"
pandas = ">=2.3.3,<3"
jupyter = ">=1.1.1,<2"
python = ">=3.12,<3.13"
logomaker = ">=0.8.6,<0.9"
ipykernel = ">=7.1.0,<8"
jupyter_client = ">=8.8.0,<9"
zeromq = ">=4.3.5,<5"
pyzmq = ">=27.1.0,<28"
line_profiler = ">=5.0.0,<6"

[pypi-dependencies]
adabmdca = ">=0.7,<0.8"
